changelog:
  categories:
    - title: Breaking Changes 💥
      labels:
        - breaking 💥
        - breaking
    - title: New Features 🎉
      labels:
        - feature ✨
        - feat
    - title: Bug Fixes 🐛
      labels:
        - fix 🐛
        - fix
    - title: Performance Improvements ⚡
      labels:
        - performance ⚡
        - perf
    - title: Testing Improvements 🧪
      labels:
        - test 🧪
        - test
    - title: Documentation 📖
      labels:
        - documentation 📖
        - docs
    - title: Dependencies 🤖
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
