name: Publish Docker Images 🐋 📦
on:
  push:
    branches:
      - main
jobs:
  build:
    concurrency:
      group: docker_image_publish
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        game: [cstrike, valve, czero, dmc, gearbox, ricochet, dod, tfc]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Set up Docker Buildx  🛠️
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub 🐳
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Replace fallback value in Dockerfile and entrypoint.sh
        run: |
          sed -i "s/\${GAME:-valve}/\${GAME:-${{ matrix.game }}}/g" Dockerfile
          sed -i "s/\${GAME:-valve}/\${GAME:-${{ matrix.game }}}/g" entrypoint.sh

      - name: Build Docker Image 🐳
        uses: docker/build-push-action@v5
        env:
          GAME: ${{ matrix.game }}
        with:
          context: .
          push: true
          tags: jives/hlds:${{ matrix.game }}
          build-args: GAME=${{ matrix.game }}

      - name: Bump Version and Create Tag 🏷️
        id: create_tag
        uses: anothrNick/github-tag-action@1.69.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Create Release 🚀
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: ${{ steps.create_tag.outputs.new_tag }}
          draft: false
          prerelease: false
