name: Publish Docker Images 🐋 📦
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Set up Docker Buildx  🛠️
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub 🐳
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image for Counter-Strike 🐳
        uses: docker/build-push-action@v2
        env:
          GAME: cstrike
        with:
          context: .
          push: true
          tags: jives/hlds:cstrike

      - name: Build Docker Image for Half-Life 🐳
        uses: docker/build-push-action@v2
        env:
          GAME: valve
        with:
          context: .
          push: true
          tags: jives/hlds:valve

      - name: Build Docker Image for Counter-Strike Condition Zero 🐳
        uses: docker/build-push-action@v2
        env:
          GAME: czero
        with:
          context: .
          push: true
          tags: jives/hlds:czero

      - name: Build Docker Image for Death Match Classic 🐳
        uses: docker/build-push-action@v2
        env:
          GAME: dmc
        with:
          context: .
          push: true
          tags: jives/hlds:dmc

      - name: Build Docker Image for Half-Life Opposing Force 🐳
        uses: docker/build-push-action@v2
        env:
          GAME: gearbox
        with:
          context: .
          push: true
          tags: jives/hlds:gearbox

      - name: Build Docker Image for Ricochet 🐳
        uses: docker/build-push-action@v2
        env:
          GAME: ricochet
        with:
          context: .
          push: true
          tags: jives/hlds:ricochet

      - name: Build Docker Image for Day of Defeat 🐳
        uses: docker/build-push-action@v2
        env:
          GAME: dod
        with:
          context: .
          push: true
          tags: jives/hlds:dod

      - name: Build Docker Image for Team Fortress Classic 🐳
        uses: docker/build-push-action@v2
        env:
          GAME: tfc
        with:
          context: .
          push: true
          tags: jives/hlds:tfc

      - name: Bump Version and Create Tag 🏷️
        id: create_tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Create Release 🚀
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: ${{ steps.create_tag.outputs.new_tag }}
          draft: false
          prerelease: false
