name: Conventional Release Labels 🏷️
on:
  pull_request_target:
    types: [opened, edited]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Label Commit
        uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: '{"feat": "feature ✨","fix": "fix 🐛","breaking": "breaking 💥","build": "build 🔧","docs": "documentation 📖","perf": "performance ⚡","revert": "revert ⏪","test": "test 🧪", "chore": "chore 🧹"}'
