name: Validate Docker Image 🐳
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Docker Buildx 🛠️
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image 🐳
        uses: docker/build-push-action@v2
        env:
          GAME: cstrike
        with:
          context: .
